package stepDefintions;// Generated by Selenium IDE


import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class AddItemsToWishlist extends driverSetup{
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    public AddItemsToWishlist(WebDriver driver) {
    }

    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driverBig = new ChromeDriver();
        js = (JavascriptExecutor) driverBig;
        vars = new HashMap<String, Object>();
    }

//    public void tearDown() {
//        driver.quit();
//    }

    public void addItemsToWishList() {
        driverBig.get("https://testscriptdemo.com/");
        driverBig.manage().window().setSize(new Dimension(1296, 736));
        driverBig.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driverBig.findElement(By.cssSelector(".elementor-shortcode:nth-child(1) .product:nth-child(1) > .product-compare-wishlist:nth-child(3) span:nth-child(2)")).click();
        driverBig.findElement(By.cssSelector(".elementor-shortcode:nth-child(1) .product:nth-child(2) > .product-compare-wishlist:nth-child(3) span:nth-child(2)")).click();
        driverBig.findElement(By.cssSelector(".elementor-shortcode:nth-child(1) .product:nth-child(3) > .product-compare-wishlist:nth-child(3) span:nth-child(2)")).click();
        {
            WebElement element = driverBig.findElement(By.cssSelector(".elementor-shortcode:nth-child(1) .product:nth-child(3) > .product-compare-wishlist:nth-child(3) span:nth-child(2)"));
            Actions builder = new Actions(driverBig);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driverBig.findElement(By.tagName("body"));
            Actions builder = new Actions(driverBig);
            builder.moveToElement(element, 0, 0).perform();
        }
        driverBig.findElement(By.cssSelector(".add-to-wishlist-23 span")).click();
    }
}
