package stepDefintions;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CartCheck {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    double cartTotal;
    String toalCart;

    public CartCheck(WebDriver driver) {
    }
    //  public void setUp() {
  //      driver = new ChromeDriver();
  //      js = (JavascriptExecutor) driver;
   //     vars = new HashMap<String, Object>();
   // }

    public void tearDown() {
        driver.quit();
    }

    public void cartCheck(WebDriver driver) {
        driver.get("https://testscriptdemo.com/");
        driver.manage().window().setSize(new Dimension(1296, 736));
        driver.findElement(By.cssSelector(".heading-row")).click();
        driver.findElement(By.cssSelector(".header-right > .header-cart .la")).click();
        toalCart = driver.findElement(By.xpath("//div/table/tbody/tr[2]")).getText();
        cartTotal = Double.parseDouble(toalCart);

    }
}
