package stepDefintions;
// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class CartCheck {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    double cartTotal;
    String toalCart;

    public CartCheck(WebDriver driver) {
    }
    //  public void setUp() {
  //      driver = new ChromeDriver();
  //      js = (JavascriptExecutor) driver;
   //     vars = new HashMap<String, Object>();
   // }

    public void tearDown() {
        driver.quit();
    }

    public void cartCheck() {

        driver.get("https://testscriptdemo.com/");
        driver.manage().window().setSize(new Dimension(1296, 736));
        driver.findElement(By.cssSelector(".heading-row")).click();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        driver.findElement(By.cssSelector(".header-right > .header-cart .la")).click();

        toalCart = driver.findElement(By.xpath("//div/table/tbody/tr[2]")).getText();
        cartTotal = Double.parseDouble(toalCart);

    }
}
