package stepDefintions;// Generated by Selenium IDE


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class LookAtWishList{
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    public LookAtWishList(WebDriver driver) {
    }

    //   public void setUp() {
 //       driver = new ChromeDriver();
 //       js = (JavascriptExecutor) driver;
 //       vars = new HashMap<String, Object>();
  //  }

 //   public void tearDown() {
 //       driver.quit();
 //   }

    public void lookAtWishList() {
       // driver.get("https://testscriptdemo.com/");
        driver.manage().window().setSize(new Dimension(1296, 736));
        driver.findElement(By.cssSelector(".header-wishlist:nth-child(3) .lar")).click();
    }
}
